services:
  postfixrelay:
    container_name: postfixrelay
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - RELAY_HOST=smtp.gmail.com
      - RELAY_PORT=465 # I have not been successful in making 587 work
      - RELAY_USER=your_email_here@gmail.com
      - RELAY_PASS=${relay_pass}
      - RELAY_SUBMISSIONS=true
      - TEST_EMAIL=test_email@domain.com # Delete after successful configuration
      - TEST_EMAIL_SUBJECT=Destroy After Reading # Delete after successful configuration
      - MYORIGIN=domain.com
      - FROMADDRESS=my_email@domain.com
      - MYNETWORKS=172.20.0.0/16
      - MSG_SIZE=30720000
      - LOG_DISABLE=false
    networks:
      - tunnel-net
    ports:
      - 25:25
    volumes:
      - ./postfixrelay/data:/var/spool/postfix # I prefer bind mounting volumes for portability
    image: loganmarchione/docker-postfixrelay:latest

networks:
  tunnel-net:
    name: tunnel-net
    external: true
